const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#FFD700",
    background: "#f5f5f5",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#FFD700",
    primaryForeground: "#0a0a0a",
    secondary: "#FF6B35",
    secondaryForeground: "#ffffff",
    muted: "#e5e5e5",
    mutedForeground: "#737373",
    accent: "#FF6B35",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#d4d4d4",
    input: "#d4d4d4",
  },
  dark: {
    text: "#f0f0f0",
    tint: "#FFD700",
    background: "#080808",
    foreground: "#f0f0f0",
    card: "#141414",
    cardForeground: "#f0f0f0",
    primary: "#FFD700",
    primaryForeground: "#0a0a0a",
    secondary: "#FF6B35",
    secondaryForeground: "#ffffff",
    muted: "#1e1e1e",
    mutedForeground: "#a3a3a3",
    accent: "#FF6B35",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
  },
  radius: 12,
};

export default colors;
